[aws]
disabled = true

[directory]
truncate_to_repo = false

[directory.substitutions]
"~/github" = "github.com"

[gcloud]
disabled = true

[nodejs]
format = "using [$symbol$version]($style) "

[package]
format = "[$symbol$version]($style) "

[php]
format = "via [$symbol$version]($style) "
symbol = "ğŸ˜ "
style = "147 bold"
disabled = false
